<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Judge Credentials – {{ $judge->name }}</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: Arial, Helvetica, sans-serif;
            font-size: 10pt;
            color: #111;
            background: #ffffff;
            margin-bottom: 60px; /* space for footer */
        }
        .page-header {
            color: #111;
            padding: 24px 24px 12px;
            text-align: center;
            border-bottom: 2px solid #040D12;
            margin-bottom: 60px;
        }
        .page-header h1 {
            font-size: 18pt;
            font-weight: bold;
            margin-bottom: 8px;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        .page-header p {
            font-size: 11pt;
            color: #444;
            margin: 4px 0;
        }
        
        .credentials-card {
            margin: 0 auto;
            width: 80%;
            border: 2px dashed #ccc;
            padding: 50px 40px;
            text-align: center;
            border-radius: 8px;
            background: #fdfdfd;
        }
        
        .role-label {
            font-size: 14pt;
            color: #666;
            margin-bottom: 15px;
            letter-spacing: 2px;
            text-transform: uppercase;
        }
        
        .judge-name {
            font-size: 28pt;
            font-weight: bold;
            color: #040D12;
            margin-bottom: 10px;
        }
        
        .judge-number {
            font-size: 16pt;
            color: #040D12;
            margin-bottom: 40px;
        }
        
        .access-label {
            font-size: 12pt;
            color: #444;
            margin-bottom: 15px;
        }
        
        .access-code {
            font-size: 42pt;
            font-family: "Courier New", Courier, monospace;
            font-weight: bold;
            color: #d4a017;
            letter-spacing: 8px;
            background: #f4f4f4;
            padding: 20px 40px;
            border: 1px solid #ddd;
            display: inline-block;
            border-radius: 8px;
        }
        
        .instructions {
            margin-top: 60px;
            font-size: 11pt;
            color: #555;
            line-height: 1.6;
            text-align: center;
            width: 80%;
            margin-left: auto;
            margin-right: auto;
        }
        
        .page-footer {
            position: fixed; 
            bottom: 0px; 
            left: 0px; 
            right: 0px;
            height: 40px; 
            line-height: 40px;
            font-size: 7.5pt;
            color: #666;
            text-align: center;
            border-top: 1px solid #ddd;
            background: #fff;
        }
    </style>
</head>
<body>

<div class="page-header">
    <h1>Judge Credentials</h1>
    <p>{{ $event ? $event->name : 'No Event Assigned' }}</p>
    @if($event && $event->date)
        <p style="font-size: 9pt; color: #777;">{{ \Carbon\Carbon::parse($event->date)->format('F j, Y') }}</p>
    @endif
</div>

<div class="credentials-card">
    <div class="role-label">Official Judge</div>
    <div class="judge-name">{{ $judge->name }}</div>
    <div class="judge-number">
        Judge Number: <strong>{{ $judge->judge_number ?? 'N/A' }}</strong>
    </div>
    
    <div class="access-label">Your Secure Login Code:</div>
    <div class="access-code">{{ $judge->login_code }}</div>
</div>

<div class="instructions">
    <p><strong>Instructions:</strong></p>
    <p>Please navigate to the tabulation portal on your device and enter the secure login code above to access your assigned event and begin scoring.</p>
    <p style="margin-top: 15px; color: #c53030; font-size: 9pt;">Do not share this code with anyone.</p>
</div>

<div class="page-footer">
    This document is auto-generated by the Tabulation System. &nbsp;|&nbsp; Powered by ECCENTRI, Inc.
</div>

</body>
</html>
